# Sample configuration file
---
products:
  - name: kubernetes
    releases:
      - "1.33"
    labels:
      aws_account: "production"
      cluster_slug: "production-logistics"
      owner_team: "sre"

  - name: postgres
    releases:
      - "17"
    labels:
      aws_account: "aaipltf-use1-prd-cnc"
      owner_team: "dbre"